{{ config(materialized='table') }}

select
    {{ dbt_utils.generate_surrogate_key(['d.delivery_id']) }} as delivery_key,
    {{ dbt_utils.generate_surrogate_key(['d.match_id']) }} as match_key,
    {{ dbt_utils.generate_surrogate_key(['d.batter']) }} as batter_key,
    {{ dbt_utils.generate_surrogate_key(['d.bowler']) }} as bowler_key,
    {{ dbt_utils.generate_surrogate_key(['d.batting_team']) }} as batting_team_key,
    d.delivery_id,
    d.match_id,
    d.innings_number,
    d.over_number,
    d.ball_number,
    d.batting_team,
    d.batter,
    d.bowler,
    d.non_striker,
    d.batter_runs,
    d.extra_runs,
    d.total_runs,
    d.wides,
    d.no_balls,
    d.byes,
    d.leg_byes,
    d.penalty_runs,
    d.player_out,
    d.dismissal_kind,
    d.is_four,
    d.is_six,
    d.is_wicket,
    d.is_illegal_delivery,
    d.source_file,
    d.loaded_at
from {{ ref('int_match_deliveries') }} d
