-- Run this script with a role allowed to create databases, warehouses, and schemas.
-- Raw tables intentionally retain source records as VARIANT; analytics models
-- should be created separately in IPL_ANALYTICS.ANALYTICS in a later phase.

CREATE DATABASE IF NOT EXISTS IPL_ANALYTICS;

CREATE WAREHOUSE IF NOT EXISTS IPL_ANALYTICS_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = FALSE
  INITIALLY_SUSPENDED = TRUE;

CREATE SCHEMA IF NOT EXISTS IPL_ANALYTICS.RAW;
CREATE SCHEMA IF NOT EXISTS IPL_ANALYTICS.ANALYTICS;

USE DATABASE IPL_ANALYTICS;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS INGESTION_METADATA (
  FILE_HASH STRING NOT NULL,
  DATASET_NAME STRING NOT NULL,
  SOURCE_FILE STRING NOT NULL,
  SOURCE_URL STRING,
  RECORD_COUNT NUMBER,
  LOADED_AT TIMESTAMP_TZ NOT NULL,
  LOAD_STATUS STRING NOT NULL,
  PRIMARY KEY (FILE_HASH)
);

CREATE TABLE IF NOT EXISTS RAW_MATCHES (
  RECORD_ID STRING NOT NULL,
  SOURCE_FILE STRING NOT NULL,
  FILE_HASH STRING NOT NULL,
  RAW_PAYLOAD VARIANT NOT NULL,
  LOADED_AT TIMESTAMP_TZ NOT NULL,
  PRIMARY KEY (RECORD_ID, FILE_HASH)
);

CREATE TABLE IF NOT EXISTS RAW_DELIVERIES LIKE RAW_MATCHES;
CREATE TABLE IF NOT EXISTS RAW_PLAYERS LIKE RAW_MATCHES;
CREATE TABLE IF NOT EXISTS RAW_TEAMS LIKE RAW_MATCHES;

-- Reserved for future curated models. Phase 3 does not populate this schema.
CREATE SCHEMA IF NOT EXISTS IPL_ANALYTICS.ANALYTICS;